apiVersion: v1
kind: Pod
metadata:
  name: news-db
  labels:
    app: news-db
spec:
  containers:
    - name: news-db-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "q1w2e3r4"
        - name: MYSQL_DATABASE
          value: "empresa"
        - name: MYSQL_PASSWORD
          value: "q1w2e3r4"
