apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-persistent
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /first-volume-persistent
          name: first-volume-persistent
  volumes:
    - name: first-volume-persistent
      persistentVolumeClaim:
        claimName: pvc-1
